import os
from typing import TypedDict, Annotated, Literal
from operator import add

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END


# 1. Initialization and Env Setup
load_dotenv(override=True)
api_key = os.getenv("GOOGLE_API_KEY")
#  Ensure GEMINI_API_KEY is set in your PyCharm environment variables
# llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.3, google_api_key=os.getenv("GOOGLE_API_KEY") )

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash", google_api_key=os.getenv("GOOGLE_API_KEY"), temperature=0
)

# 2. Define Custom Tools
@tool
def calculate_server_density(cores: int, VMs: int) -> str:
    """Calculates the density ratio of virtual machines per CPU core."""
    if cores <= 0:
        return "Core count must be greater than zero."
    ratio = VMs / cores
    return f"The server density ratio is {ratio:.2f} VMs per CPU core."


# Bind tools directly to the Gemini LLM
tools = [calculate_server_density]
llm_with_tools = llm.bind_tools(tools)


# 3. Define Graph State
class AgentState(TypedDict):
    # messages list appends new items automatically via the 'add' operator
    messages: Annotated[list[BaseMessage], add]


# 4. Define Nodes (Execution Blocks)
def call_model(state: AgentState) -> dict:
    """Executes the LLM with the historical message state."""
    messages = state["messages"]
    # Provide system context if empty
    if not messages or not isinstance(messages[0], SystemMessage):
        messages = [
            SystemMessage(content="You are an expert infrastructure engineer.")
        ] + messages

    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}


def execute_tools(state: AgentState) -> dict:
    """Processes tool calls generated by the model node."""
    messages = state["messages"]
    last_message = messages[-1]

    tool_outputs = []
    # Execute tools sequentially if called by the LLM
    if hasattr(last_message, "tool_calls"):
        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]

            if tool_name == "calculate_server_density":
                result = calculate_server_density.invoke(tool_args)
                # Tool messages must mirror the unique tool_call_id
                tool_outputs.append(
                    AIMessage(
                        content=str(result), name=tool_name, id=tool_call["id"]
                    )
                )

    return {"messages": tool_outputs}


# 5. Define Routing Logic
def route_after_model(state: AgentState) -> Literal["execute_tools", END]:
    """Determines whether to loop into tool execution or terminate."""
    last_message = state["messages"][-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "execute_tools"
    return END


# 6. Build the Graph
workflow = StateGraph(AgentState)

# Add functional nodes
workflow.add_node("call_model", call_model)
workflow.add_node("execute_tools", execute_tools)

# Configure flow paths
workflow.add_edge(START, "call_model")
workflow.add_conditional_edges("call_model", route_after_model)
workflow.add_edge("execute_tools", "call_model")

# Compile into an executable application
app = workflow.compile()

# 7. Run Example in PyCharm
if __name__ == "__main__":
    print("--- Running Basic Tool Agent ---")
    query = "We have 16 cores and 72 VMs running. What is our density ratio?"
    inputs = {"messages": [HumanMessage(content=query)]}

    for chunk in app.stream(inputs):
        for node, state in chunk.items():
            print(f"\n[Node: {node}]")
            print(f"Latest Message: {state['messages'][-1].content}")
